package tetris.engine.mechanics;

public class CallBack {
/**==============================================================================
 *  This class allows screen update events to be forwarded to the interface any
 *  time there is movement in the shape, whether generated by the gravity system
 *  or by user input from the interface. (ie. input from the interface will cause
 *  a call back to occur even though the interface may be aware of the need to 
 *  update the screen already, in this case just ignore the call back to avaoid 
 *  updating the screen needlessly)
 *  ringBell() is called only by the Tetris Engine, It is the job of the
 *  interface developer to ensure this method reaches their interface.
 *  Either insert a method call into this code, or extend the class and 
 *  override the method.
 *  =============================================================================
 */
	public void ringBell() {
		// interface call back goes here
	}
}
